language: ruby

services:
  - postgresql
  - docker

rvm:
  - 2.4.2
  - 2.5.0

cache: bundler

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - docker version
  - docker-compose version

  - docker-compose -f docker-compose-lightweight.yml up -d

  - docker ps

  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate

script:
  - bundle exec rails test
  - bundle exec rails test:system
  - bundle exec rubocop
  - bundle exec scss-lint
